{{- if and .Values.postgresql.enabled .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tarnished.fullname" . }}-postgresql
  labels:
    {{- include "tarnished.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password }}
{{- end }}
