{{/* Validate PostgreSQL configuration */}}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) (not .Values.postgresql.password) }}
{{- fail "postgresql.enabled=true requires either postgresql.password or postgresql.existingSecret to be set" }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tarnished.fullname" . }}-postgresql
  labels:
    {{- include "tarnished.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
